import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";
import { useQueryClient } from "@tanstack/react-query";
import { useRouter } from "next/router";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import React from "react";

const pollSchema = z.object({
  title: z.string().min(1, { message: "title is required" }),
  description: z
    .string()
    .min(15, { message: "please provider a short description of your poll" }),
});

interface addPollProps {
  title: string;
  description: string;
}

const Home: NextPage = () => {
  const router = useRouter();
  const utils = trpc.useContext();
  const { data: sessionData } = useSession();
  const polls = trpc.poll.getAll.useQuery(undefined, {
    enabled: sessionData?.user !== undefined,
  });
  const {
    register,
    handleSubmit,
    reset,
    formState: { errors },
  } = useForm({ resolver: zodResolver(pollSchema) });

  const addPoll = trpc.poll.addPoll.useMutation({
    onSuccess: async () => {
      utils.poll.getAll.invalidate();
      reset();
    },
  });

  const handleAddPoll = ({ title, description }: addPollProps) => {
    addPoll.mutate({
      title: title,
      description: description,
    });
  };

  return (
    <>
      <Head>
        <title>ExcelSurvey</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <AuthShowcase />
        <div className="flex flex-row flex-wrap items-center gap-6">
          {polls.data?.map((poll) => (
            <article key={poll.id} className="bg-purple-300 p-4">
              <h3>{poll.title}</h3>
              <p>{poll.description}</p>
            </article>
          ))}
        </div>
        <div className="mt-10" />
        <form
          onSubmit={handleSubmit((values) =>
            handleAddPoll({
              title: values.title,
              description: values.description,
            })
          )}
        >
          <div>
            <>
              <input {...register("title")} />
              {errors.title?.message}
              <textarea {...register("description")} />
              {errors.description?.message}

              <button
                type="submit"
                className={`rounded-full bg-purple-600 px-8 py-2 hover:bg-purple-400 active:bg-purple-700 ${
                  addPoll.isLoading && "bg-gray-400"
                } `}
                disabled={addPoll.isLoading}
              >
                Add Poll
              </button>
            </>
          </div>
        </form>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData?.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
